name: Docker CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-docker-build:
    uses: ./.github/workflows/reusable-docker-build.yml

    with:
      image_name: two-tier-flask-app-gitactions

    secrets:
      docker_user: ${{ secrets.DOCKER_USER }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}