name: Test Docker Compose Up

on:
  workflow_dispatch:

jobs:
  compose-up:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: DockerHub Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      
      - name: Docker pull image
        run: docker compose pull 


      - name: Start App Using Docker Compose
        run: docker compose up -d

      - name: Check Running Containers
        run: docker ps

      - name: Check Compose Services
        run: docker compose ps
