name: Docker build ci


on: 
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  
  docker-build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout -repo
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t two-tier-flask-app-gitactions:latest .

        
