name: Docker build ci


on: 
  workflow_dispatch:
    push:
      branches:
        - main

env:
  IMAGE_NAME: two-tier-flask-app-gitactions

jobs:
  
  docker-build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout -repo
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t $IMAGE_NAME .

      - name: docker image tag 
        run:  docker tag $IMAGE_NAME ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest

      - name: docker login 
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USER}}" --password-stdin

      

      - name: docker push
        run: docker push ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest
