name: reusable-docker-build.yml

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      docker_user:
        required: true
      docker_password:
        required: true
      

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: build and push using composite
        uses: ./.github/actions/docker-build-push
        with:
          docker_user: ${{secrets.docker_user}}
          docker_password: ${{secrets.docker_password}}
          image_name: ${{inputs.image_name}}
        
  
